version: '3.3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  mariadb:
    build: ./requirements/mariadb
    environment:
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: rel-fagr
      MARIADB_PASSWORD: 123456789
  wordpress: 
    build: ./requirements/wordpress
    volumes:
     - ./wordpress:/var/www/html:delegated