version: '3.3'

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/garra/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/garra/data/wordpress
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadbmake
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress: 
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
     - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: always
  static_web_site:
    build: ./requirements/bonus/web
    container_name: static_web_site
    ports:
      - "3001:3001"
    networks:
      - inception
    env_file:
      - .env
    restart: always