version: '3.3'

networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress: 
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
     - ./wordpress:/var/www/html:delegated
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always