version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  mariadb:
    build:
      context: .
      dockerfile: mariadb.dockerfile
    environment:
      MARIADB_DATABASE: wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
     - ./wordpress:/var/www/html:delegated